### ISSUE TITLE
[Bug]: Call to undefined method App\Models\User::getFilamentAvatarUrl()

### ISSUE THREAD

**Issue by Jacobtims** [noxoua/filament-activity-log#44]
### What happened?

I installed the package for the first time and created the "Activities" page, according to the documentation.
When I visit the activities page the following error occurred:

![image](https://github.com/noxoua/filament-activity-log/assets/75219092/b030ebcf-908c-4513-9479-ecc084b2aac3)

Can be fixed by adding this to the User class:
```php
public function getFilamentAvatarUrl(): string
{
    return '';
}
```

### How to reproduce the bug

- composer require noxoua/filament-activity-log
- Create a page in your pages folder app/Filament/Pages/ and extends the ListActivities class
- Visit the Activities page

### Package Version

2.1.5

### PHP Version

8.2.11

### Laravel Version

10.26.2

### Which operating systems does with happen with?

macOS

**Comment by noxoua** [comment]
In the `getFilamentAvatarUrl` method, you should return a URL pointing to the user's avatar. If the user model does not include an avatar, please return null.

```php
public function getFilamentAvatarUrl(): ?string
{
    return null;
}
```

For more information, refer to the [Filament documentation](https://filamentphp.com/docs/3.x/panels/users#setting-up-user-avatars).
