### ISSUE TITLE
[Bug]: Class name must be a valid object or a string

### ISSUE THREAD

**Issue by Jacobtims** [noxoua/filament-activity-log#45]
### What happened?

After I fixed the `getFilamentAvatarUrl()` in my User class,  the following error occurred:

![image](https://github.com/noxoua/filament-activity-log/assets/75219092/cb979bc3-8a80-43e7-bb57-405bd64a1db5)

### How to reproduce the bug

- composer require noxoua/filament-activity-log
- Create a page in your pages folder app/Filament/Pages/ and extends the ListActivities class
- Visit the Activities page

### Package Version

2.1.5

### PHP Version

8.2.11

### Laravel Version

10.26.2

### Which operating systems does with happen with?

macOS

**Comment by noxoua** [comment]
Share the error please

<img width="783" alt="Screenshot 2023-11-10 at 10 28 16" src="https://github.com/noxoua/filament-activity-log/assets/142592979/ad9568ac-77e5-44ff-b68e-d3fb0c15ed44">
