### ISSUE TITLE
[Bug]: Property App\Filament\Pages\Activities::$filters.subject_type does not exist

### ISSUE THREAD

**Issue by MarJose123** [noxoua/filament-activity-log#54]
### What happened?

Applying a filter then refreshing the page cause an error.

### How to reproduce the bug

1. Setup the and follow the instruction https://activity-log.noxo.app/get-started
2. Go to the `Activities` Resource on your browser
3. Apply filter (any `subject` field value will do)
4. Refresh the page

### Package Version

^2

### PHP Version

8.1

### Laravel Version

10.0

### Which operating systems does with happen with?

Linux

### Notes

The issue also occur on the https://activity-log.noxo.app/link-causer-subject functionality

**Comment by noxoua** [comment]
Thank you for submitting the issue 🙏  The bug has been fixed in the latest version 🐛
