### ISSUE TITLE
[Bug]: Filament\FilamentManager::getUserAvatarUrl(): Argument #1 ($user) must be of type Authenticatable, null given

### ISSUE THREAD

**Issue by a-zog** [noxoua/filament-activity-log#56]
### What happened?

When accessing the activities, an error occurs:
```
Filament\FilamentManager::getUserAvatarUrl(): Argument #1 ($user) must be of type Illuminate\Database\Eloquent\Model|Illuminate\Contracts\Auth\Authenticatable, null given
called in /vendor/noxoua/filament-activity-log/src/Pages/Concerns/HasListFilters.php on line 151
```

### How to reproduce the bug

Go to all activities url (in the panel)

### Package Version

latest

### PHP Version

8.2.6

### Laravel Version

10.39.0

### Which operating systems does with happen with?

macOS

**Comment by noxoua** [comment]
Looks like you have outdated data in your db. try to clear `activity_log` table

**Comment by a-zog** [comment]
Yes, that was that, thank you 🙏
