### ISSUE TITLE
[Bug]: wrong "use" path for Filament Resource when using the makeLogger Command

### ISSUE THREAD

**Issue by Davide7h** [noxoua/filament-activity-log#57]
### What happened?

Running the php artisan make:filament-logger ModelName command causes the right logger to be created, but instead of using App\Filament\Resources\ModelNameResource, it uses App\Filament\Loggers\ModelNameResource, which doesn't exist. So I get an error unless I manually edit each and every path from the created loggers. 

I don't know if it's me doing something wrong, but with the previous versione everything ran smoothly without this kind of behaviour

### How to reproduce the bug

Whenever I run the command the resources is imported in the logger from the wrong path

### Package Version

2.1.92

### PHP Version

8.2.12

### Laravel Version

10.10

### Which operating systems does with happen with?

macOS

**Comment by Davide7h** [comment]
Update: Even after manually correcting the path I now see the activities page but I no longer see the details about the updated models, nor the time of the update

![Screenshot 2024-01-07 alle 00 50 14](https://github.com/noxoua/filament-activity-log/assets/68255376/13478dbe-b4dd-4040-a794-749b5371dd67)

**Comment by noxoua** [comment]
Hi @Davide7h  👋

1. use path bug - fixed
2. could you please share code of your logger file

**Comment by Davide7h** [comment]
Hello, noxoua, thank you for the fix. Unfortunately I don't have that logger file anymore, because I rolled the library back to a previous version. As soon as I will have the time to try and update it again I will gladly provide it, should the issue arise again (it will probabily not, though).

Thanks again and keep up the great work!
