### ISSUE TITLE
[Bug]: Error  avatar

### ISSUE THREAD

**Issue by DeviJv** [noxoua/filament-activity-log#58]
### What happened?

Filament\FilamentManager::getUserAvatarUrl(): Argument #1 ($user) must be of type Illuminate\Database\Eloquent\Model|Illuminate\Contracts\Auth\Authenticatable, null given, called in C:\project\Cash-Craft\vendor\noxoua\filament-activity-log\src\Pages\Concerns\HasListFilters.php on line 151

### How to reproduce the bug

just access the page activities in tutorial

### Package Version

2.0

### PHP Version

8.2

### Laravel Version

10

### Notes

Filament\FilamentManager::getUserAvatarUrl(): Argument #1 ($user) must be of type Illuminate\Database\Eloquent\Model|Illuminate\Contracts\Auth\Authenticatable, null given, called in C:\project\Cash-Craft\vendor\noxoua\filament-activity-log\src\Pages\Concerns\HasListFilters.php on line 151

**Comment by noxoua** [comment]
Hi @DeviJv 👋

This bug has been fixed, please upgrade the package to the latest version (2.2.0)
