### ISSUE TITLE
[Bug]: Attempted to lazy load [causer] on model [Spatie\Activitylog\Models\Activity] but lazy loading is disabled.

### ISSUE THREAD

**Issue by piotrh052b** [noxoua/filament-activity-log#60]
### What happened?

Cannot display activity log if Model lazy loading is disabled.

### How to reproduce the bug

Add Model::shouldBeStrict(); in AppServiceProvider boot() method.
Make some changes in records.
Try to display Activity history.

### Package Version

2.2.0

### PHP Version

8.1

### Laravel Version

10.41

### Which operating systems does with happen with?

Windows

**Comment by piotrh052b** [comment]
I think I found a solution by overriding the getActivities() method

` public function getActivities()
    {
        return $this->paginateTableQuery(
            $this->applyFilters(Activity::with(['causer'])->latest())
        );
    }`
    
Is this a correct solution ?

**Comment by afsakar** [comment]
It's seems fixed but you didn't add last release this PR.
