### ISSUE TITLE
[Bug]: Activity data doesn't appear correctly

### ISSUE THREAD

**Issue by dimyatiutoyo** [noxoua/filament-activity-log#69]
### What happened?

activity data is not showing
![Screenshot 2024-03-18 170834](https://github.com/noxoua/filament-activity-log/assets/42503512/67e6a0e3-9f6c-4c91-afcf-68570e75ef84)

### How to reproduce the bug

I follow the tutorial, but i use panel feature in my app.

### Package Version

2.2

### PHP Version

8.1

### Laravel Version

10.10

### Which operating systems does with happen with?

Windows

**Comment by nbartokos** [comment]
Hey!
Did you make a logger for your resource? I have experienced the same "error", that it didn't show any entries while saying "1 of 3 showing".
After creating a logger "php artisan make:filament-logger <resource>" the entries appeared in my activity log.

**Comment by dimyatiutoyo** [comment]
Yeah, I made a logger for a resource. I ran the command `php artisan make:filament-logger` and create the logger, but it was same. I will check again

**Comment by dimyatiutoyo** [comment]
I found the problem. Publish the config `php artisan vendor:publish --tag="filament-activity-log-config"`, then change the config to your directory and namespace of the loggers, example:
```
'loggers' => [
        'directory' => app_path('Filament/Loggers'), // app_path('Filament/App/Loggers') 
        'namespace' => 'App\\Filament\\Loggers', // 'App\\Filament\\App\\Loggers'
    ],
```
